steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/de-uitdaging-dev', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/de-uitdaging-dev']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'de-uitdaging-dev', '--image', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]', '--region', 'europe-west1','--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/de-uitdaging-dev]