steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/de-uitdaging', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/de-uitdaging']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'de-uitdaging', '--image', 'gcr.io/$PROJECT_ID/de-uitdaging', '--region', 'europe-west1','--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/de-uitdaging
